version: '3.1'

services:

  db:
    container_name: mysite_postgres
    image: postgres:10.2
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: mysite-postgresql

  adminer:
    container_name: mysite_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
